#!/usr/bin/env Rscript

# TargetQC flat-output plot generator.
# Input: one TargetQC output directory containing files named <prefix>_*.tsv.
# Output: PNG files used by reports/TargetQC_report.Rmd.

suppressPackageStartupMessages({ library(ggplot2); library(dplyr); library(tidyr); library(readr); library(stringr); library(scales); library(patchwork); library(grid); library(rlang) })
if (requireNamespace("ggpubr", quietly = TRUE)) has_ggpubr <- TRUE else has_ggpubr <- FALSE

args <- commandArgs(trailingOnly = TRUE)
get_arg <- function(key, default = "") { idx <- which(args == key); if (length(idx) == 0 || idx[[1]] == length(args)) return(default); args[[idx[[1]] + 1]] }
input_root <- path.expand(get_arg("--input-root", "."))
output_root <- path.expand(get_arg("--output-root", file.path(input_root, "figures")))
prefix <- get_arg("--prefix")
sample_type <- tolower(get_arg("--sample-type", "clinical"))
seq_type <- toupper(get_arg("--seq", "ES"))
dp_high <- as.numeric(get_arg("--dp-high", "30"))
dp_low <- as.numeric(get_arg("--dp-low", "20"))
baf_threshold <- as.numeric(get_arg("--baf-threshold", "0.05"))
gene_level_range <- get_arg("--gene-level-range", "≥30X")
selected_gene_type <- get_arg("--selected-gene-type", "protein_coding")
plot_dpi <- as.numeric(get_arg("--plot-dpi", "300"))
if (!nzchar(prefix)) stop("--prefix is required")
dir.create(output_root, recursive = TRUE, showWarnings = FALSE)

file_of <- function(suffix) file.path(input_root, paste0(prefix, suffix))
out_of <- function(name) file.path(output_root, paste0(prefix, "_", name))
clean_names <- function(x) { x <- sub("^#", "", x); x <- gsub("^X\.30X$|^X\.\.30X$", "≥30X", x); x <- gsub("^X\.20X$|^X\.\.20X$", "≥20X", x); x <- gsub("^X\.10X$|^X\.\.10X$", "≤10X", x); x <- gsub("^X10\.20X$|^X10_20X$|^X10-20X$", "10-20X", x); x <- gsub("^X20\.30X$|^X20_30X$|^X20-30X$", "20-30X", x); x }
read_targetqc_tsv <- function(file_path) { if (!file.exists(file_path)) { message("[Missing] ", file_path); return(NULL) }; first <- readLines(file_path, n = 1, warn = FALSE); if (length(first) == 0) return(NULL); first <- sub("^\ufeff", "", first); if (substr(first, 1, 1) == "#") { cols <- strsplit(sub("^#", "", first), "\t")[[1]]; dat <- readr::read_tsv(file_path, skip = 1, col_names = cols, col_types = cols(.default = col_character()), show_col_types = FALSE, progress = FALSE) } else { dat <- readr::read_tsv(file_path, col_types = cols(.default = col_character()), show_col_types = FALSE, progress = FALSE) }; dat <- as.data.frame(dat, check.names = FALSE, stringsAsFactors = FALSE); colnames(dat) <- clean_names(colnames(dat)); dat }
safe_numeric <- function(x) suppressWarnings(as.numeric(gsub("[,%]", "", as.character(x))))
require_columns <- function(dat, cols, name = "") { if (is.null(dat)) return(FALSE); miss <- setdiff(cols, colnames(dat)); if (length(miss) > 0) { message("[", name, "] Missing columns: ", paste(miss, collapse = ", ")); return(FALSE) }; TRUE }
empty_plot <- function(label = "No data available") ggplot() + annotate("text", x = 0.5, y = 0.5, label = label, size = 6) + xlim(0, 1) + ylim(0, 1) + theme_void()
save_plot <- function(p, file, width = 8, height = 6) { ggsave(file, p, width = width, height = height, dpi = plot_dpi, bg = "white"); message("[Saved] ", file) }
theme_targetqc <- function() theme_classic(base_size = 16) + theme(axis.line = element_line(color = "black", linewidth = 0.5), axis.ticks = element_line(color = "black", linewidth = 0.5), axis.title = element_text(size = 24), axis.text = element_text(size = 18, colour = "black"), panel.grid.major.y = element_line(color = "gray90", linewidth = 0.3), panel.grid.major.x = element_blank(), panel.grid.minor = element_blank())

plot_exon_base <- function(input_file, output_file) { dat <- read_targetqc_tsv(input_file); if (!require_columns(dat, c("thresholds", "percent"), "exon_base")) return(save_plot(empty_plot("No exon base data"), output_file)); plot_dat <- dat %>% mutate(threshold = safe_numeric(gsub("X", "", .data$thresholds)), percent = safe_numeric(.data$percent)) %>% filter(is.finite(.data$threshold), is.finite(.data$percent)) %>% arrange(.data$threshold); if (nrow(plot_dat) == 0) return(save_plot(empty_plot("No valid exon base data"), output_file)); p <- ggplot(plot_dat, aes(x = .data$threshold, y = .data$percent)) + geom_line(linewidth = 1, color = "#0072B2") + geom_point(size = 3, color = "#0072B2") + geom_text(aes(label = sprintf("%.2f%%", .data$percent)), vjust = -0.7, size = 5) + scale_x_continuous(breaks = plot_dat$threshold, labels = paste0(plot_dat$threshold, "X")) + scale_y_continuous(limits = c(0, 100), breaks = seq(0, 100, 10), expand = expansion(mult = c(0, 0.08))) + labs(x = "Coverage Threshold", y = "Percentage of Target Regions (%)") + theme_targetqc(); save_plot(p, output_file) }
prepare_exon_summary <- function(dat) { if (!require_columns(dat, c("capture", "well", "middle", "poor", "capture_total"), "exon_summary")) return(NULL); dat %>% mutate(capture = str_remove(as.character(.data$capture), "_capture$"), well = safe_numeric(.data$well), middle = safe_numeric(.data$middle), poor = safe_numeric(.data$poor), capture_total = safe_numeric(.data$capture_total)) }
plot_exon_summary <- function(input_file, output_file) { dat <- prepare_exon_summary(read_targetqc_tsv(input_file)); if (is.null(dat)) return(save_plot(empty_plot("No exon summary data"), output_file)); total_row <- dat %>% filter(.data$capture %in% c("coverage_total", "full")); if (nrow(total_row) == 0) total_row <- dat; total <- max(total_row$capture_total, na.rm = TRUE); if (!is.finite(total) || total <= 0) return(save_plot(empty_plot("No valid exon summary"), output_file)); counts <- total_row[1, c("well", "middle", "poor")]; plot_dat <- data.frame(group = factor(c("well covered", "middle covered", "poor covered"), levels = c("well covered", "middle covered", "poor covered")), count = as.numeric(counts[1, ])); plot_dat$Percentage <- plot_dat$count / total * 100; p <- ggplot(plot_dat, aes(x = .data$group, y = .data$Percentage)) + geom_col(fill = "#C1A8DC", width = 0.35, color = "black", linewidth = 0.5) + geom_text(aes(label = sprintf("%.2f%%", .data$Percentage)), vjust = -0.5, size = 6, fontface = "bold") + scale_y_continuous(limits = c(0, 100), breaks = seq(0, 100, 10), expand = expansion(mult = c(0, 0.08))) + labs(x = NULL, y = "Percentage (%)") + theme_targetqc(); save_plot(p, output_file) }
plot_gene_cdf <- function(input_file, output_file) { dat <- read_targetqc_tsv(input_file); if (!require_columns(dat, c("gene_id", "gene_name", "gene_type"), "gene_cdf")) return(save_plot(empty_plot("No gene data"), output_file)); if (!gene_level_range %in% colnames(dat)) return(save_plot(empty_plot(paste("Column not found:", gene_level_range)), output_file)); data_use <- dat; if (selected_gene_type == "protein_coding") data_use <- data_use %>% filter(.data$gene_type == "protein_coding"); if (selected_gene_type == "pseudogene") data_use <- data_use %>% filter(str_detect(.data$gene_type, "pseudogene")); if (selected_gene_type == "others") data_use <- data_use %>% filter(.data$gene_type != "protein_coding", !str_detect(.data$gene_type, "pseudogene")); plot_dat <- data_use %>% transmute(prop = safe_numeric(.data[[gene_level_range]])) %>% filter(is.finite(.data$prop)) %>% arrange(.data$prop); if (nrow(plot_dat) == 0) return(save_plot(empty_plot("No valid gene data"), output_file)); cdf <- plot_dat %>% mutate(count_above = n():1); p <- ggplot(cdf, aes(x = .data$prop, y = .data$count_above)) + geom_line(linewidth = 1.3, linetype = "dashed", color = "#0072B2") + scale_x_continuous(limits = c(0, 100), breaks = seq(0, 100, 10)) + labs(x = paste0(gene_level_range, " fraction (%)"), y = "Gene Count", title = paste0("Genes: ", nrow(cdf))) + theme_targetqc() + theme(plot.title = element_text(hjust = 0.5)); save_plot(p, output_file) }
plot_gene_summary <- function(input_file, output_file) { dat <- read_targetqc_tsv(input_file); if (!require_columns(dat, c("coverage_quality"), "gene_summary")) return(save_plot(empty_plot("No gene summary data"), output_file)); if ("percentage" %in% colnames(dat)) { plot_dat <- dat %>% mutate(Percentage = safe_numeric(.data$percentage)); if (max(plot_dat$Percentage, na.rm = TRUE) <= 1) plot_dat$Percentage <- plot_dat$Percentage * 100 } else if ("percent" %in% colnames(dat)) { plot_dat <- dat %>% mutate(Percentage = safe_numeric(.data$percent)); if (max(plot_dat$Percentage, na.rm = TRUE) <= 1) plot_dat$Percentage <- plot_dat$Percentage * 100 } else if ("count" %in% colnames(dat)) { total <- sum(safe_numeric(dat$count), na.rm = TRUE); plot_dat <- dat %>% mutate(Percentage = safe_numeric(.data$count) / total * 100) } else { return(save_plot(empty_plot("No percentage/count column"), output_file)) }; plot_dat <- plot_dat %>% filter(is.finite(.data$Percentage)); if (nrow(plot_dat) == 0) return(save_plot(empty_plot("No valid gene summary"), output_file)); p <- ggplot(plot_dat, aes(x = .data$coverage_quality, y = .data$Percentage)) + geom_col(fill = "#C1A8DC", width = 0.35, color = "black", linewidth = 0.5) + geom_text(aes(label = sprintf("%.2f%%", .data$Percentage)), vjust = -0.5, size = 6, fontface = "bold") + scale_y_continuous(limits = c(0, max(100, max(plot_dat$Percentage, na.rm = TRUE) * 1.15)), expand = expansion(mult = c(0, 0.08))) + labs(x = NULL, y = "Percentage (%)") + theme_targetqc(); save_plot(p, output_file) }

normalize_variant_capture <- function(dat) { if (is.null(dat)) return(dat); if (!"var_type" %in% colnames(dat) && "variant_type" %in% colnames(dat)) dat <- dat %>% rename(var_type = variant_type); if (!"BAF" %in% colnames(dat) && all(c("AD_alt", "DP") %in% colnames(dat))) dat <- dat %>% mutate(BAF = safe_numeric(.data$AD_alt) / safe_numeric(.data$DP)); dat }
plot_variant_capture_dp <- function(input_file, output_file) { dat <- normalize_variant_capture(read_targetqc_tsv(input_file)); if (!require_columns(dat, c("DP"), "variant_capture_dp")) return(save_plot(empty_plot("No variant DP data"), output_file)); dat <- dat %>% mutate(DP = safe_numeric(.data$DP)) %>% filter(is.finite(.data$DP)); if (nrow(dat) == 0) return(save_plot(empty_plot("No valid DP data"), output_file)); dp_pct <- dat %>% mutate(DP_group = case_when(.data$DP >= dp_high ~ paste0("DP≥", dp_high), .data$DP <= dp_low ~ paste0("DP≤", dp_low), TRUE ~ NA_character_)) %>% filter(!is.na(.data$DP_group)) %>% count(.data$DP_group) %>% mutate(Percentage = .data$n / nrow(dat) * 100); if (nrow(dp_pct) == 0) return(save_plot(empty_plot("No DP sites matched thresholds"), output_file)); p <- ggplot(dp_pct, aes(x = .data$DP_group, y = .data$Percentage, fill = .data$DP_group)) + geom_col(width = 0.35, color = "black", linewidth = 0.5) + geom_text(aes(label = sprintf("%.2f%%", .data$Percentage)), vjust = -0.5, size = 6, fontface = "bold") + scale_fill_manual(values = c(setNames("#1f77b4", paste0("DP≥", dp_high)), setNames("#e41a1c", paste0("DP≤", dp_low)))) + scale_y_continuous(limits = c(0, 100), breaks = seq(0, 100, 10), expand = expansion(mult = c(0, 0.08))) + labs(x = NULL, y = "Percentage (%)", title = paste0("DP ≥", dp_high, " vs DP ≤", dp_low)) + theme_targetqc() + theme(legend.position = "none", plot.title = element_text(hjust = 0.5)); save_plot(p, output_file) }
make_baf_panel <- function(dat, genotype_value, title_text, y_label) { panel <- dat %>% filter(.data$genotype == genotype_value); if (nrow(panel) == 0) return(empty_plot(paste("No", genotype_value, "BAF data"))); stats <- panel %>% group_by(.data$variant_type) %>% summarise(total = n(), good = sum(.data$counts <= baf_threshold, na.rm = TRUE), .groups = "drop") %>% mutate(label = sprintf("%.1f%%", .data$good / .data$total * 100), y = max(panel$counts, na.rm = TRUE) * 1.08); ggplot(panel, aes(x = .data$variant_type, y = .data$counts, fill = .data$variant_type)) + geom_violin(trim = FALSE, alpha = 0.8) + geom_boxplot(width = 0.12, outlier.size = 0.5) + geom_text(data = stats, aes(x = .data$variant_type, y = .data$y, label = .data$label), inherit.aes = FALSE, size = 5, fontface = "bold") + labs(title = title_text, x = NULL, y = y_label) + theme_targetqc() + theme(legend.position = "none", plot.title = element_text(hjust = 0.5)) }
plot_variant_capture_baf <- function(input_file, output_file) { dat <- normalize_variant_capture(read_targetqc_tsv(input_file)); if (!require_columns(dat, c("genotype", "BAF", "var_type"), "variant_capture_baf")) return(save_plot(empty_plot("No variant BAF data"), output_file, 8, 10)); plot_dat <- dat %>% mutate(BAF = safe_numeric(.data$BAF), genotype = case_when(tolower(.data$genotype) %in% c("het", "heterozygous", "0/1", "1/0", "0|1", "1|0") ~ "het", tolower(.data$genotype) %in% c("hom", "homozygous", "1/1", "1|1", "1") ~ "hom", TRUE ~ tolower(.data$genotype)), variant_type = case_when(toupper(.data$var_type) %in% c("SNP", "SNV") ~ "SNV", toupper(.data$var_type) %in% c("INDEL", "INS", "DEL") ~ "Indel", TRUE ~ as.character(.data$var_type)), counts = case_when(.data$genotype == "hom" ~ abs(1 - .data$BAF), .data$genotype == "het" ~ abs(.data$BAF - 0.5), TRUE ~ NA_real_)) %>% filter(.data$genotype %in% c("het", "hom"), !is.na(.data$variant_type), is.finite(.data$counts)); if (nrow(plot_dat) == 0) return(save_plot(empty_plot("No valid BAF data"), output_file, 8, 10)); p <- make_baf_panel(plot_dat, "het", "Het Genotype", "|BAF - 0.5|") / make_baf_panel(plot_dat, "hom", "Hom Genotype", "1 - BAF"); save_plot(p, output_file, 8, 10) }

GeomSplitViolin <- ggproto("GeomSplitViolin", GeomViolin, draw_group = function(self, data, ..., draw_quantiles = NULL) { data <- transform(data, xminv = x - violinwidth * (x - xmin), xmaxv = x + violinwidth * (xmax - x)); grp <- data[1, "group"]; newdata <- transform(data, x = if (grp %% 2 == 1) xminv else xmaxv); newdata <- newdata[order(if (grp %% 2 == 1) newdata$y else -newdata$y), ]; newdata <- rbind(newdata[1, ], newdata, newdata[nrow(newdata), ], newdata[1, ]); newdata[c(1, nrow(newdata)-1, nrow(newdata)), "x"] <- round(newdata[1, "x"]); ggplot2:::ggname("geom_split_violin", GeomPolygon$draw_panel(newdata, ...)) })
geom_split_violin <- function(mapping = NULL, data = NULL, stat = "ydensity", position = "identity", ..., trim = TRUE, scale = "area", na.rm = FALSE, show.legend = NA, inherit.aes = TRUE) layer(data = data, mapping = mapping, stat = stat, geom = GeomSplitViolin, position = position, show.legend = show.legend, inherit.aes = inherit.aes, params = list(trim = trim, scale = scale, na.rm = na.rm, ...))
normalize_variant_calling <- function(dat) { if (is.null(dat)) return(dat); if (!"type" %in% colnames(dat) && "tpfpfn" %in% colnames(dat)) dat <- dat %>% rename(type = tpfpfn); if (!"variant_type" %in% colnames(dat) && "var_type" %in% colnames(dat)) dat <- dat %>% rename(variant_type = var_type); if (!"BAF" %in% colnames(dat) && all(c("AD_alt", "DP") %in% colnames(dat))) dat <- dat %>% mutate(BAF = safe_numeric(.data$AD_alt) / safe_numeric(.data$DP)); if (!"BAF" %in% colnames(dat) && all(c("AD_ref", "AD_alt") %in% colnames(dat))) dat <- dat %>% mutate(BAF = safe_numeric(.data$AD_alt) / (safe_numeric(.data$AD_ref) + safe_numeric(.data$AD_alt))); if ("type" %in% colnames(dat)) dat <- dat %>% mutate(type = toupper(as.character(.data$type))); if ("variant_type" %in% colnames(dat)) dat <- dat %>% mutate(variant_type = case_when(toupper(.data$variant_type) %in% c("SNP", "SNV") ~ "SNV", toupper(.data$variant_type) %in% c("INDEL", "INS", "DEL", "INSERTION", "DELETION") ~ "Indel", TRUE ~ as.character(.data$variant_type))); if ("genotype" %in% colnames(dat)) dat <- dat %>% mutate(genotype = case_when(tolower(.data$genotype) %in% c("het", "heterozygous", "0/1", "1/0", "0|1", "1|0") ~ "het", tolower(.data$genotype) %in% c("hom", "homozygous", "1/1", "1|1", "1") ~ "hom", TRUE ~ tolower(.data$genotype))); dat }
plot_variant_calling_dp <- function(input_file, output_file) { dat <- normalize_variant_calling(read_targetqc_tsv(input_file)); if (!require_columns(dat, c("type", "DP"), "variant_calling_dp")) return(save_plot(empty_plot("No variant calling DP data"), output_file)); plot_dat <- dat %>% mutate(value = safe_numeric(.data$DP), group = factor(.data$type, levels = c("TP", "FN")), sample = "Sample") %>% filter(is.finite(.data$value), .data$value > 0, .data$group %in% c("TP", "FN")); if (nrow(plot_dat) == 0) return(save_plot(empty_plot("No valid TP/FN DP data"), output_file)); p <- ggplot(plot_dat, aes(x = .data$sample, y = .data$value, fill = .data$group)) + geom_split_violin(trim = TRUE, colour = "white", scale = "width") + stat_summary(fun = median, geom = "point", position = position_dodge(width = 0.1), size = 2, show.legend = FALSE) + stat_summary(fun.min = function(x) quantile(x, 0.25, na.rm = TRUE), fun.max = function(x) quantile(x, 0.75, na.rm = TRUE), geom = "errorbar", color = "black", width = 0.05, position = position_dodge(width = 0.1), show.legend = FALSE) + scale_fill_manual(values = c("TP" = "#93aeda", "FN" = "#9fcb98"), limits = c("TP", "FN")) + labs(x = "", y = "DP") + theme_bw(base_size = 16) + theme(axis.text.x = element_blank(), axis.ticks.x = element_blank(), legend.position = "top", legend.title = element_blank()); if (has_ggpubr && n_distinct(plot_dat$group) == 2) p <- p + ggpubr::stat_compare_means(aes(group = .data$group), method = "wilcox.test", label = "p.signif", hide.ns = TRUE, label.y = max(plot_dat$value, na.rm = TRUE) * 1.1); save_plot(p, output_file, 6, 6) }
make_calling_baf_panel <- function(plot_dat, genotype_value, title_text, y_label) { panel <- plot_dat %>% filter(.data$genotype == genotype_value); if (nrow(panel) == 0) return(empty_plot(paste("No", genotype_value, "BAF data"))); p <- ggplot(panel, aes(x = .data$variant_type, y = .data$counts, fill = .data$type)) + geom_split_violin(trim = TRUE, colour = "white", scale = "width") + stat_summary(fun = median, geom = "point", position = position_dodge(width = 0.1), size = 2, show.legend = FALSE) + stat_summary(fun.min = function(x) quantile(x, 0.25, na.rm = TRUE), fun.max = function(x) quantile(x, 0.75, na.rm = TRUE), geom = "errorbar", color = "black", width = 0.05, position = position_dodge(width = 0.1), show.legend = FALSE) + scale_fill_manual(values = c("TP" = "#93aeda", "FP" = "#f69b80"), limits = c("TP", "FP")) + labs(title = title_text, x = "", y = y_label) + theme_bw(base_size = 16) + theme(plot.title = element_text(hjust = 0.5), legend.position = "top", legend.title = element_blank()); if (has_ggpubr) { label_y <- max(panel$counts, na.rm = TRUE) * 1.1; for (vt in c("SNV", "Indel")) { tmp <- panel %>% filter(.data$variant_type == vt, .data$type %in% c("TP", "FP")); if (nrow(tmp) > 0 && n_distinct(tmp$type) == 2) p <- p + ggpubr::stat_compare_means(data = tmp, aes(group = .data$type), method = "wilcox.test", label = "p.signif", hide.ns = TRUE, label.y = label_y) } }; p }
plot_variant_calling_baf <- function(input_file, output_file) { dat <- normalize_variant_calling(read_targetqc_tsv(input_file)); if (!require_columns(dat, c("type", "genotype", "variant_type", "BAF", "DP"), "variant_calling_baf")) return(save_plot(empty_plot("No variant calling BAF data"), output_file, 8, 10)); plot_dat <- dat %>% mutate(BAF = safe_numeric(.data$BAF), DP = safe_numeric(.data$DP), variant_type = factor(.data$variant_type, levels = c("SNV", "Indel")), type = factor(.data$type, levels = c("TP", "FP")), genotype = factor(.data$genotype, levels = c("het", "hom")), counts = case_when(.data$genotype == "hom" ~ abs(1 - .data$BAF), .data$genotype == "het" ~ abs(.data$BAF - 0.5), TRUE ~ NA_real_)) %>% filter(.data$type %in% c("TP", "FP"), .data$genotype %in% c("het", "hom"), !is.na(.data$variant_type), is.finite(.data$counts), is.finite(.data$DP), .data$DP > 0); if (nrow(plot_dat) == 0) return(save_plot(empty_plot("No valid TP/FP BAF data"), output_file, 8, 10)); p <- make_calling_baf_panel(plot_dat, "het", "Het Genotype", "|BAF - 0.5|") / make_calling_baf_panel(plot_dat, "hom", "Hom Genotype", "1 - BAF"); save_plot(p, output_file, 8, 10) }

message("=====================================================")
message("[TargetQC flat plot] prefix = ", prefix)
message("=====================================================")
plot_exon_base(file_of("_base.tsv"), out_of("plot1_a.png"))
plot_exon_summary(file_of("_exon_capture_QC.summary.tsv"), out_of("qualified_exons.png"))
plot_gene_cdf(file_of("_trans.tsv"), out_of("gene_all.png"))
plot_gene_summary(file_of("_gene_capture_QC.summary.tsv"), out_of("gene_percent_all.png"))

if (file.exists(file_of("_variant_capture_QC.tsv"))) { plot_variant_capture_dp(file_of("_variant_capture_QC.tsv"), out_of("variant_capture_QC_plot_DP.png")); plot_variant_capture_baf(file_of("_variant_capture_QC.tsv"), out_of("variant_capture_QC_plot_BAF.png")) }
if (file.exists(file_of("_region_variant_capture_QC.tsv"))) { plot_variant_capture_dp(file_of("_region_variant_capture_QC.tsv"), out_of("region_variant_capture_QC_plot_DP.png")); plot_variant_capture_baf(file_of("_region_variant_capture_QC.tsv"), out_of("region_variant_capture_QC_plot_BAF.png")) }
if (file.exists(file_of("_variant_calling_QC.tsv"))) { plot_variant_calling_dp(file_of("_variant_calling_QC.tsv"), out_of("variant_calling_QC_plot_DP_TP_FN.png")); plot_variant_calling_baf(file_of("_variant_calling_QC.tsv"), out_of("variant_calling_QC_plot_BAF_TP_FP.png")) }
if (file.exists(file_of("_region_variant_calling_QC.tsv"))) { plot_variant_calling_dp(file_of("_region_variant_calling_QC.tsv"), out_of("region_variant_calling_QC_plot_DP_TP_FN.png")); plot_variant_calling_baf(file_of("_region_variant_calling_QC.tsv"), out_of("region_variant_calling_QC_plot_BAF_TP_FP.png")) }
