#!/usr/bin/env python3
"""
target_coverage.py - Generate mosdepth commands for coverage analysis
"""

import os
import sys
import argparse
import glob

def main():
    class CustomHelpFormatter(argparse.HelpFormatter):
        def _format_action_invocation(self, action):
            if not action.option_strings:
                metavar, = self._metavar_formatter(action, action.dest)(1)
                return metavar
            else:
                parts = []
                if action.nargs == 0:
                    parts.extend(action.option_strings)
                else:
                    
                    default = self._get_default_metavar_for_optional(action)
                    args_string = self._format_args(action, default)
                    for option_string in action.option_strings:
                        parts.append(option_string)
                    
                return ', '.join(parts)

    parser = argparse.ArgumentParser(
        description='Generate mosdepth commands for coverage analysis',
        usage='capture_coverage.py --bam <file.bam> --regions <regions.bed> --out <outprefix>',
        formatter_class=CustomHelpFormatter,
        add_help=False
    )

    parser.add_argument('-h', '--help', action='help', default=argparse.SUPPRESS,
                       help='show this help message and exit')
    
    # Required arguments
    required = parser.add_argument_group('Required options')
    required.add_argument('--bam', required=True, metavar='<file.bam>', help='Input BAM files of the sample')
    required.add_argument('--regions', required=True, metavar='<regions.bed>', help='BED file for the target region')
    required.add_argument('--out', required=True, metavar='<outprefix>', help='Prefix to name output files')
    required.add_argument('--mosdepth-path', 
                         metavar='<path>',
                         help='Path to mosdepth executable')
    # Optional arguments
    optional = parser.add_argument_group('Additional general options')
    optional.add_argument('--thresholds', default='10,20,30,40',
                         metavar='<10,20,30,40>',  
                         help='Coverage thresholds (comma-separated, default: 10,20,30,40)')

    args = parser.parse_args()
    
    # Check if input files exist
    if not os.path.exists(args.bam):
        print(f"Error: BAM file {args.bam} does not exist.")
        sys.exit(1)
    
    if not os.path.exists(args.regions):
        print(f"Error: BED file {args.regions} does not exist.")
        sys.exit(1)
    
    # Check if mosdepth path exists and is executable
    if not os.path.isfile(args.mosdepth_path) or not os.access(args.mosdepth_path, os.X_OK):
        print(f"Error: mosdepth executable not found or not executable: {args.mosdepth_path}")
        sys.exit(1)
    
    # Create output directory if it doesn't exist
    output_dir = os.path.dirname(args.out) if os.path.dirname(args.out) else '.'
    if not os.path.exists(output_dir):
        os.makedirs(output_dir, exist_ok=True)
        print(f"Created output directory: {output_dir}")
    
    # Set default bash file name
    bash_file = f'{args.out}.sh'    
    # Generate mosdepth command
    with open(bash_file, 'w') as mosdepth_script:
        mosdepth_script.write("#!/bin/bash\n")
        mosdepth_script.write("# Generated by capture_coverage.py\n")
        mosdepth_script.write("# This script runs mosdepth coverage analysis\n\n")
        
        # Build the mosdepth command using the provided path
        mosdepth_command = f"{args.mosdepth_path} -t 4 --by {args.regions} --thresholds {args.thresholds}"
        
        # Add output prefix and input BAM
        mosdepth_command += f" {args.out} {args.bam}"
        
        mosdepth_script.write(mosdepth_command + "\n")
        
        # Make the script executable
        os.chmod(bash_file, 0o755)
    
    print(f"Generated mosdepth command in {bash_file}")
    print(f"Command: {mosdepth_command}")
    print(f"To execute: bash {bash_file}")

if __name__ == "__main__":
    main()

